### ISSUE TITLE
Compilation error with SuiteSparse and NumPy on Ubuntu 24.04

### ISSUE THREAD

**Issue by Fernandovilelab** [scikit-umfpack/scikit-umfpack#101]
I am  trying to installl using pip install . but it gets this error:

meson setup /home/fernando/Documents/scikit-umfpack /home/fernando/Documents/scikit-umfpack/.mesonpy-wqmrpe48 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/home/fernando/Documents/scikit-umfpack/.mesonpy-wqmrpe48/meson-python-native-file.ini
      The Meson build system
      Version: 1.4.1
      Source dir: /home/fernando/Documents/scikit-umfpack
      Build dir: /home/fernando/Documents/scikit-umfpack/.mesonpy-wqmrpe48
      Build type: native build
      Project name: scikits.umfpack
      Project version: 0.4.1
      C compiler for the host machine: cc (gcc 13.2.0 "cc (Ubuntu 13.2.0-23ubuntu4) 13.2.0")
      C linker for the host machine: cc ld.bfd 2.42
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Program python found: YES (/home/fernando/.local/bin/python3)
      Program swig found: YES (/usr/bin/swig)
      Found pkg-config: YES (/usr/bin/pkg-config) 1.8.1
      Run-time dependency openblas found: YES 0.3.26
      Run-time dependency umfpack found: YES 6.3.2
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Run-time dependency python found: YES 3.12
      Build targets in project: 2
      
      scikits.umfpack 0.4.1
      
        User defined options
          Native files: /home/fernando/Documents/scikit-umfpack/.mesonpy-wqmrpe48/meson-python-native-file.ini
          buildtype   : release
          b_ndebug    : if-release
          b_vscrt     : md
      
      Found ninja-1.11.1.git.kitware.jobserver-1 at /tmp/pip-build-env-jw2zyvxg/normal/bin/ninja
      + /tmp/pip-build-env-jw2zyvxg/normal/bin/ninja
      [1/3] Generating scikits/umfpack/_umfpack_swig with a custom command
      /usr/include/suitesparse/umfpack.h:86: Warning 202: Could not evaluate expression '!defined (SUITESPARSE__VERSION) || \
          (SUITESPARSE__VERSION < SUITESPARSE__VERCODE(7,6,0))'
      /usr/include/suitesparse/umfpack.h:86: Warning 202: Syntax error: expected operator
      /usr/include/suitesparse/umfpack.h:91: Warning 202: Could not evaluate expression '!defined (AMD__VERSION) || \
          (AMD__VERSION < SUITESPARSE__VERCODE(3,3,1))'
      /usr/include/suitesparse/umfpack.h:91: Warning 202: Syntax error: expected operator
      [2/3] Compiling C object scikits/umfpack/__umfpack.cpython-312-x86_64-linux-gnu.so.p/meson-generated_..__umfpack_wrap.c.o
      FAILED: scikits/umfpack/__umfpack.cpython-312-x86_64-linux-gnu.so.p/meson-generated_..__umfpack_wrap.c.o
      cc -Iscikits/umfpack/__umfpack.cpython-312-x86_64-linux-gnu.so.p -Iscikits/umfpack -I../scikits/umfpack -I../../../../../tmp/pip-build-env-jw2zyvxg/overlay/lib/python3.12/site-packages/numpy/_core/include -I/usr/include/x86_64-linux-gnu/openblas-pthread/ -I/usr/include/suitesparse -I/usr/include/python3.12 -I/usr/include/x86_64-linux-gnu/python3.12 -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O3 -fPIC -Wno-misleading-indentation -Wno-incompatible-pointer-types -MD -MQ scikits/umfpack/__umfpack.cpython-312-x86_64-linux-gnu.so.p/meson-generated_..__umfpack_wrap.c.o -MF scikits/umfpack/__umfpack.cpython-312-x86_64-linux-gnu.so.p/meson-generated_..__umfpack_wrap.c.o.d -o scikits/umfpack/__umfpack.cpython-312-x86_64-linux-gnu.so.p/meson-generated_..__umfpack_wrap.c.o -c scikits/umfpack/_umfpack_wrap.c
      In file included from ../../../../../tmp/pip-build-env-jw2zyvxg/overlay/lib/python3.12/site-packages/numpy/_core/include/numpy/ndarraytypes.h:1909,
                       from ../../../../../tmp/pip-build-env-jw2zyvxg/overlay/lib/python3.12/site-packages/numpy/_core/include/numpy/ndarrayobject.h:12,
                       from ../../../../../tmp/pip-build-env-jw2zyvxg/overlay/lib/python3.12/site-packages/numpy/_core/include/numpy/arrayobject.h:5,
                       from scikits/umfpack/_umfpack_wrap.c:3189:
      ../../../../../tmp/pip-build-env-jw2zyvxg/overlay/lib/python3.12/site-packages/numpy/_core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
         17 | #warning "Using deprecated NumPy API, disable it with " \
            |  ^~~~~~~
      scikits/umfpack/_umfpack_wrap.c: In function ‘_wrap_umfpack_di_symbolic’:
      scikits/umfpack/_umfpack_wrap.c:3642:71: error: ‘PyArray_DOUBLE’ undeclared (first use in this function); did you mean ‘PyArray_DTYPE’?
       3642 |     PyArrayObject *obj;    obj = helper_getCArrayObject( swig_obj[4], PyArray_DOUBLE, 1, 1 );    if (!obj) return NULL;    arg5 = (double *) obj->data;    Py_DECREF( obj );

**Comment by FranckBoyer** [comment]
Hi,

I have essentially the same problem here (Ubuntu 20.04.4)
```
     + meson setup /tmp/pip-install-cmntbkla/scikit-umfpack_17305359b290404f8f8298b85e08f65b /tmp/pip-install-cmntbkla/scikit-umfpack_17305359b290404f8f8298b85e08f65b/.mesonpy-lef02gsd -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-install-cmntbkla/scikit-umfpack_17305359b290404f8f8298b85e08f65b/.mesonpy-lef02gsd/meson-python-native-file.ini
      The Meson build system
      Version: 1.4.1
      Source dir: /tmp/pip-install-cmntbkla/scikit-umfpack_17305359b290404f8f8298b85e08f65b
      Build dir: /tmp/pip-install-cmntbkla/scikit-umfpack_17305359b290404f8f8298b85e08f65b/.mesonpy-lef02gsd
      Build type: native build
      Project name: scikits.umfpack
      Project version: 0.4.1
      C compiler for the host machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
      C linker for the host machine: cc ld.bfd 2.38
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Program python found: YES (/home/fboyer/temp/test_umfpack/venv/bin/python)
      Program swig found: YES (/usr/bin/swig)
      Found pkg-config: YES (/usr/bin/pkg-config) 0.29.2
      Run-time dependency openblas found: YES 0.3.20
      Found CMake: /usr/bin/cmake (3.22.1)
      Run-time dependency umfpack found: NO (tried pkgconfig and cmake)
      Has header "umfpack.h" : YES
      Library umfpack found: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Run-time dependency python found: YES 3.10
      Build targets in project: 2
      
      scikits.umfpack 0.4.1
      
        User defined options
          Native files: /tmp/pip-install-cmntbkla/scikit-umfpack_17305359b290404f8f8298b85e08f65b/.mesonpy-lef02gsd/meson-python-native-file.ini
          buildtype   : release
          b_ndebug    : if-release
          b_vscrt     : md
      
      Found ninja-1.11.1.git.kitware.jobserver-1 at /tmp/pip-build-env-1y1stwo0/normal/bin/ninja
      + /tmp/pip-build-env-1y1stwo0/normal/bin/ninja
      [1/3] Generating scikits/umfpack/_umfpack_swig with a custom command
      [2/3] Compiling C object scikits/umfpack/__umfpack.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__umfpack_wrap.c.o
      FAILED: scikits/umfpack/__umfpack.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__umfpack_wrap.c.o
      cc -Iscikits/umfpack/__umfpack.cpython-310-x86_64-linux-gnu.so.p -Iscikits/umfpack -I../scikits/umfpack -I../../../pip-build-env-1y1stwo0/overlay/lib/python3.10/site-packages/numpy/_core/include -I/usr/include/suitesparse -I/usr/local/include -I/usr/include/x86_64-linux-gnu/openblas-pthread/ -I/usr/include/python3.10 -I/usr/include/x86_64-linux-gnu/python3.10 -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O3 -fPIC -Wno-misleading-indentation -Wno-incompatible-pointer-types -MD -MQ scikits/umfpack/__umfpack.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__umfpack_wrap.c.o -MF scikits/umfpack/__umfpack.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__umfpack_wrap.c.o.d -o scikits/umfpack/__umfpack.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__umfpack_wrap.c.o -c scikits/umfpack/_umfpack_wrap.c
      In file included from ../../../pip-build-env-1y1stwo0/overlay/lib/python3.10/site-packages/numpy/_core/include/numpy/ndarraytypes.h:1909,
                       from ../../../pip-build-env-1y1stwo0/overlay/lib/python3.10/site-packages/numpy/_core/include/numpy/ndarrayobject.h:12,
                       from ../../../pip-build-env-1y1stwo0/overlay/lib/python3.10/site-packages/numpy/_core/include/numpy/arrayobject.h:5,
                       from scikits/umfpack/_umfpack_wrap.c:2707:
      ../../../pip-build-env-1y1stwo0/overlay/lib/python3.10/site-packages/numpy/_core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
         17 | #warning "Using deprecated NumPy API, disable it with " \
            |  ^~~~~~~
```

I have `libsuitesparse-dev/jammy,now 1:5.10.1+dfsg-4build1` installed.

I've tried with different version of python and there is still the same error.

Any idea of what is happening ?

Thanks for the support.
Best,

**Comment by n8downs** [comment]
FYI, I was able to work around this error by rolling back to `scikit-umfpack==0.3.3`.

**Comment by rmotah** [comment]
Hi,

I have this problem here with Windows and Anaconda.

`Processing d:\github\scikit-umfpack
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [431 lines of output]
      + meson setup D:\GitHub\scikit-umfpack D:\GitHub\scikit-umfpack\.mesonpy-in7ygbjw -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=D:\GitHub\scikit-umfpack\.mesonpy-in7ygbjw\meson-python-native-file.ini
      The Meson build system
      Version: 1.5.0
      Source dir: D:\GitHub\scikit-umfpack
      Build dir: D:\GitHub\scikit-umfpack\.mesonpy-in7ygbjw
      Build type: native build
      Project name: scikits.umfpack
      Project version: 0.4.1
      C compiler for the host machine: ccache gcc (gcc 13.1.0 "gcc (MinGW-W64 x86_64-msvcrt-posix-seh, built by Brecht Sanders) 13.1.0")
      C linker for the host machine: gcc ld.bfd 2.40
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Program python found: YES (D:\GitHub\PowerEng\.conda\python.exe)
      Program swig found: YES (C:\Users\rmota\AppData\Local\Temp\pip-build-env-2gxf__b5\overlay\Scripts\swig.EXE)
      Found pkg-config: YES (D:\GitHub\PowerEng\.conda\Library\mingw-w64\bin\pkg-config.EXE) 0.29.1
      Run-time dependency openblas found: YES 0.3.27
      Did not find CMake 'cmake'
      Found CMake: NO
      Run-time dependency umfpack found: NO (tried pkgconfig and cmake)
      Has header "umfpack.h" : YES
      Library umfpack found: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Run-time dependency python found: YES 3.11
      Build targets in project: 2

      scikits.umfpack 0.4.1

        User defined options
          Native files: D:\GitHub\scikit-umfpack\.mesonpy-in7ygbjw\meson-python-native-file.ini
          buildtype   : release
          b_ndebug    : if-release
          b_vscrt     : md

      Found ninja.EXE-1.11.1 at C:\Strawberry\c\bin\ninja.EXE
      + meson compile
      [1/3] Generating scikits/umfpack/_umfpack_swig with a custom command
      [2/3] Compiling C object scikits/umfpack/__umfpack.cp311-win_amd64.pyd.p/meson-generated_..__umfpack_wrap.c.obj
      FAILED: scikits/umfpack/__umfpack.cp311-win_amd64.pyd.p/meson-generated_..__umfpack_wrap.c.obj
      "ccache" "gcc" "-Iscikits\umfpack\__umfpack.cp311-win_amd64.pyd.p" "-Iscikits\umfpack" "-I..\scikits\umfpack" "-IC:\Users\rmota\AppData\Local\Temp\pip-build-env-2gxf__b5\overlay\Lib\site-packages\numpy\_core\include" "-IC:\Users\rmota\anaconda3\pkgs\suitesparse-7.0.1-ha3e4fde_0\Library\include" "-ID:/bld/openblas_1720424725455/_h_env/Library/include/openblas" "-ID:\GitHub\PowerEng\.conda\Include" "-fvisibility=hidden" "-fdiagnostics-color=always" "-DNDEBUG" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-std=c99" "-O3" "-DMS_WIN64=" "-Wno-misleading-indentation" "-Wno-incompatible-pointer-types" -MD -MQ scikits/umfpack/__umfpack.cp311-win_amd64.pyd.p/meson-generated_..__umfpack_wrap.c.obj -MF "scikits\umfpack\__umfpack.cp311-win_amd64.pyd.p\meson-generated_..__umfpack_wrap.c.obj.d" -o scikits/umfpack/__umfpack.cp311-win_amd64.pyd.p/meson-generated_..__umfpack_wrap.c.obj "-c" scikits/umfpack/_umfpack_wrap.c
      In file included from C:\Users\rmota\AppData\Local\Temp\pip-build-env-2gxf__b5\overlay\Lib\site-packages\numpy\_core\include/numpy/ndarraytypes.h:1909,
                       from C:\Users\rmota\AppData\Local\Temp\pip-build-env-2gxf__b5\overlay\Lib\site-packages\numpy\_core\include/numpy/ndarrayobject.h:12,
                       from C:\Users\rmota\AppData\Local\Temp\pip-build-env-2gxf__b5\overlay\Lib\site-packages\numpy\_core\include/numpy/arrayobject.h:5,
                       from scikits/umfpack/_umfpack_wrap.c:3195:
      C:\Users\rmota\AppData\Local\Temp\pip-build-env-2gxf__b5\overlay\Lib\site-packages\numpy\_core\include/numpy/npy_1_7_deprecated_api.h:14:9: note: '#pragma message: C:\Users\rmota\AppData\Local\Temp\pip-build-env-2gxf__b5\overlay\Lib\site-packages\numpy\_core\include/numpy/npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION'`

**Comment by rmotah** [comment]
I'm facing same problems to install on Windows 10 with anaconda plataform.

Found ninja.EXE-1.11.1 at C:\Strawberry\c\bin\ninja.EXE
      + meson compile
      [1/3] Generating scikits/umfpack/_umfpack_swig with a custom command
      [2/3] Compiling C object scikits/umfpack/__umfpack.cp311-win_amd64.pyd.p/meson-generated_..__umfpack_wrap.c.obj
      FAILED: scikits/umfpack/__umfpack.cp311-win_amd64.pyd.p/meson-generated_..__umfpack_wrap.c.obj
      "ccache" "gcc" "-Iscikits\umfpack\__umfpack.cp311-win_amd64.pyd.p" "-Iscikits\umfpack" "-I..\scikits\umfpack" "-IC:\Users\rmota\AppData\Local\Temp\pip-build-env-1gabjxxc\overlay\Lib\site-packages\numpy\_core\include" "-IC:\Users\rmota\anaconda3\pkgs\suitesparse-7.0.1-ha3e4fde_0\Library\include" "-ID:/bld/openblas_1720424725455/_h_env/Library/include/openblas" "-ID:\GitHub\PowerEng\.conda\Include" "-fvisibility=hidden" "-fdiagnostics-color=always" "-DNDEBUG" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-std=c99" "-O3" "-DMS_WIN64=" "-Wno-misleading-indentation" "-Wno-incompatible-pointer-types" -MD -MQ scikits/umfpack/__umfpack.cp311-win_amd64.pyd.p/meson-generated_..__umfpack_wrap.c.obj -MF "scikits\umfpack\__umfpack.cp311-win_amd64.pyd.p\meson-generated_..__umfpack_wrap.c.obj.d" -o scikits/umfpack/__umfpack.cp311-win_amd64.pyd.p/meson-generated_..__umfpack_wrap.c.obj "-c" scikits/umfpack/_umfpack_wrap.c
      In file included from C:\Users\rmota\AppData\Local\Temp\pip-build-env-1gabjxxc\overlay\Lib\site-packages\numpy\_core\include/numpy/ndarraytypes.h:1909,
                       from C:\Users\rmota\AppData\Local\Temp\pip-build-env-1gabjxxc\overlay\Lib\site-packages\numpy\_core\include/numpy/ndarrayobject.h:12,
                       from C:\Users\rmota\AppData\Local\Temp\pip-build-env-1gabjxxc\overlay\Lib\site-packages\numpy\_core\include/numpy/arrayobject.h:5,
                       from scikits/umfpack/_umfpack_wrap.c:3195:
      C:\Users\...\AppData\Local\Temp\pip-build-env-1gabjxxc\overlay\Lib\site-packages\numpy\_core\include/numpy/npy_1_7_deprecated_api.h:14:9: note: '#pragma message: C:\Users\rmota\AppData\Local\Temp\pip-build-env-1gabjxxc\overlay\Lib\site-packages\numpy\_core\include/numpy/npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION'

**Comment by JohnDN90** [comment]
I was able to get around this error by adding `#include "numpy/old_defines.h"` after [this line in umfpack.i ](https://github.com/scikit-umfpack/scikit-umfpack/blob/0.4.1/scikits/umfpack/umfpack.i#L14), so that it looks like

```
%{
#include <umfpack.h>
#include "numpy/arrayobject.h"
#include "numpy/old_defines.h"
%}
```
I haven't really looked into this error much, but I suspect it has something to do with newer versions of NumPy.  In my case, I was using NumPy 1.26.4, scikit-umfpack 0.4.1, and SuiteSparse 5.13.0.  Again, because I haven't looked into it much, I don't know if my workaround above is the most appropriate fix, but it does allow me to compile scikit-umfpack and doing a simple test with `spsolve` and `splu` seems to work.

**Comment by carlosal1015** [comment]
Does not work, because it [was removed](https://numpy.org/doc/stable/release/2.0.0-notes.html#numpy-2-0-c-api-removals).

> The numpy/old_defines.h which was part of the API deprecated since NumPy 1.7 has been removed. This removes macros of the form PyArray_CONSTANT. The [replace_old_macros.sed](https://github.com/numpy/numpy/blob/main/tools/replace_old_macros.sed) script may be useful to convert them to the NPY_CONSTANT version.

```
scikits/umfpack/_umfpack_wrap.c:3197:10: fatal error: numpy/old_defines.h: No such file or directory
 3197 | #include "numpy/old_defines.h"
```

**Comment by oliverrinne** [comment]
Same problem on my Mac (M1 chip), using Python 3.12.3, scikit-umfpack 0.4.1, numpy 2.1.2 and SuiteSparse 7.8.2.

The following hack worked for me: In umfpack.h (located in /opt/homebrew/Cellar/suite-sparse/7.8.2/include/suitesparse on my machine), add the following line after line 26:
#define PyArray_DOUBLE   NPY_DOUBLE

Still, this needs to be fixed.
