### ISSUE TITLE
move repo to scikit-umfpack organization

### ISSUE THREAD

**Issue by rc** [scikit-umfpack/scikit-umfpack#13]
Hi @pv, @cmutel, @timtadh,

I would like to transfer this repository under scikit-umfpack organization (just created). The reason is that I want to be able to create pull-requests as @rc, and splitting the main repo from my personal account seems like a good step. I will proceed as follows:

1. transfer the repository, as described at https://help.github.com/articles/transferring-a-repository/
2. make a quick release 0.2.1. It cannot be 0.2, see #11, where I screwed things up - this release will fix the #11 problem - I will test in at https://testpypi.python.org/pypi.
3. I will do PRs happily ever after...

Do you agree? Comments welcome!
r.

**Comment by rc** [comment]
So it is possible for me to create PRs (see #14, #15) after all. But nevertheless, moving the main repository under scikit-umfpack organization still seems a good idea to me :)

**Comment by timtadh** [comment]
seems fine to me. the organization route seems like the better way to go on github at the moment.

**Comment by cmutel** [comment]
This is fine with me!

**Comment by rc** [comment]
It's done, so beware of warts! I plan to make a release ASAP so that PyPi links are updated. If you find anything I have missed/am missing, let me know, please.

**Comment by rc** [comment]
Step 2 (0.2.1 release) is done.

**Comment by cmutel** [comment]
Updated OS X wheels here:

https://dl.dropboxusercontent.com/u/1911208/scikit_umfpack-0.2.1-cp27-none-macosx_10_6_intel.whl

https://dl.dropboxusercontent.com/u/1911208/scikit_umfpack-0.2.1-cp34-cp34m-macosx_10_6_intel.whl

**Comment by rc** [comment]
@cmutel Thanks! The wheels are uploaded.

**Comment by cmutel** [comment]
Might as well have a wheel for 3.5 as well:

https://dl.dropboxusercontent.com/u/1911208/scikit_umfpack-0.2.1-cp35-cp35m-macosx_10_6_intel.whl

**Comment by rc** [comment]
Thanks again!
