### ISSUE TITLE
undefined symbol: SuiteSparse_config

### ISSUE THREAD

**Issue by sbecuwe** [scikit-umfpack/scikit-umfpack#16]
I'm using numpy 1.9.2, scipy 0.16.0, Python 2.7.10, SuiteSparse 4.4.5 and scikit-umfpack from github (to avoid the lib.six problem from #11).
In numpy's site.cfg, I followed the instructions on http://rc.github.io/scikit-umfpack/install.html

However, entering
```
  from scikits import umfpack
```
results in
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/scikit-umfpack/0.2-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/scikits/umfpack/__init__.py", line 12, in <module>
    from .umfpack import *
  File "[...]/scikit-umfpack/0.2-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/scikits/umfpack/umfpack.py", line 130, in <module>
    from . import _umfpack as _um
  File "[...]/scikit-umfpack/0.2-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/scikits/umfpack/_umfpack.py", line 28, in <module>
    __umfpack = swig_import_helper()
  File "[...]/scikit-umfpack/0.2-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/scikits/umfpack/_umfpack.py", line 24, in swig_import_helper
    _mod = imp.load_module('__umfpack', fp, pathname, description)
ImportError: [...]/scikit-umfpack/0.2-intel-2015b-Python-2.7.10/lib/python2.7/site-packages/scikits/umfpack/__umfpack.so: undefined symbol: SuiteSparse_config  
```

Adding the directory where libsuitesparseconfig.a is located (in SuiteSparse_config in the SuiteSparse directory) to site.cfg doesn't help.

Any idea how to fix this?

**Comment by rc** [comment]
Hi @sbecuwe, could you try adding the missing library into ``umf_info['libraries']`` in ``scikits/umfpack/setup.py``? Similarly to ``librt``, see #10.

**Comment by sbecuwe** [comment]
It turned out that by reading Stefan Fürtinger's instructions, I got it working. You could maybe update the url to his page: http://fuertinger.lima-city.de/research.html seems to be the up-to-date version.

**Comment by rc** [comment]
OK, thanks for the info. BTW. after a quick glance at the original link, I do not see differences in the instructions - is something wrong in the ones in the original url? Both pages have the same date of the last update, so IMHO they are in sync.

So, for posterity, what was the actual problem?

**Comment by sbecuwe** [comment]
There are some minor (typographical) changes/fixes on the new page which show pages are not in sync. The new url is also his current home page.
The actual problem: the shared libs were missing in my SparseSuite.

**Comment by rc** [comment]
OK, I have added PR #20 - could you review? :)

**Comment by sbecuwe** [comment]
Done! Checked url ;-) Thanks for the update.

**Comment by rc** [comment]
It's merged. Thanks, and let us close this.
