### ISSUE TITLE
Enable travis-CI

### ISSUE THREAD

**Issue by pv** [scikit-umfpack/scikit-umfpack#17]
Enabling travis-ci to run tests for each pull request may be useful. Travis should have suitesparse packages, so it's probably possible to use it.

**Comment by rc** [comment]
OK, that would be useful. I do not have any experience with that. [1] seem easy, but a help with writing a good ``.travis.yml`` would be appreciated.

[1] http://docs.travis-ci.com/user/getting-started/

**Comment by rc** [comment]
Done in PR #18.
