### ISSUE TITLE
Access umfpack_dl* Routines (64Bit Integer)

### ISSUE THREAD

**Issue by RobertKosik** [scikit-umfpack/scikit-umfpack#22]
Hello,

Is there any way to access the 64Bit-Versions?
The di_versions are limited to 4GB (or even 2GB).

Platform is Linux AMD64 gcc (CentOS/Ubuntu).

I try:

[First preprocess mtx: csc-format, order_indices etc.]
umf = scikits.umfpack.UmfpackContext('dl') # default 'di'
(status,umf._symbolic)=umf.funs.symbolic(nrow,ncol,indptr,indx,data,umf.control,umf.info)

[Passing in all matrix parameters as numpy.int64 arrays, i.e.:]
indx = numpy.array(mtx.indices,dtype='int64')
nrow = numpy.int64(mtx.shape[0])
etc.

Error Message:
in method 'umfpack_dl_symbolic', argument 1 of type 'SuiteSparse_long'

> /usr/local/lib/python2.7/dist-packages/scikits/umfpack/_umfpack.py(465)umfpack_dl_symbolic()

I played around with the data types but could not fix this (passing in int32 or c_longlong from ctypes did not work either).

I would appreciate any workaround, even if it is only a temporary dirty "hack".
Thank you for this work!

Best regards,
Robert

**Comment by rc** [comment]
Hi,

IMHO this is not possible at the moment - see ``umfpack.i``. We should probably update it to use SuiteSparse_long instead of int/long where appropriate. Also ``umfFamilyTypes`` and other places in ``umfpack.py`` seem to be int-only.

**Comment by RobertKosik** [comment]
Robert, thank you for the replay.

Unfortunately I have a very limited understanding of how swig works. 
I know how to make Fortran binding from numpy using f2py - but that is it.

So umfpack.i looks very cryptic to me. [Not even sure, if that is related to swig at all.]

Actually, I spent two full days trying to get umfpack to work. Seems that all the other python sparse libraries have the same problem. 

I had only had the vague feeling, that the scikit version is "almost there". 

The umfpack headers contain SuiteSparse_long which during installation of SuiteSparse gets translated to long on a gcc 64bit arch (if properly configured).

My hope was to tell swig, that "SuiteSparse_long" in the headers should be interpreted as long.
Or even going through the header files read by swig and replace "SuiteSparse_long" with long manually. And run setup.py again? If that could work? 

Yeah, very limited unterstanding. :-)

I worry less about umfpack.py. If the raw bindings are there, that is - hopefully - enough.

Again, thanks for this work!

**Comment by rc** [comment]
I will try to address this soon(ish). Do not hesitate to post new findings if any in the meantime :)

r.

**Comment by RobertKosik** [comment]
Thank you, Robert.

I'd like to add some remarks concerning the compilation of SuiteSparse for 64 bits.

Many reports about installation problems on the net. The default installation compiles
both *di* and *dl* routines, but they are all 32 bits.

Download is here: http://faculty.cse.tamu.edu/davis/suitesparse.html

Some relevant info with respect to 32 and 64 bit versions can be found in the
Umfpack User Guide (file UMFPACK/Doc/UMFPACK_UserGuide.pdf). 

Section 5.1 "The size of an integer" (page 13):
"If you compile UMFPACK and AMD in the LP64 mode, be sure to add -DLP64 to the
compilation command. See the examples in the SuiteSparse_config/SuiteSparse_config.mk
file."

Not sure, if this info is outdated, because I cannot find any compile option "-DLP64"
in file SuiteSparse_config.mk. This might be a generic option for make - no idea. 
(Seems that -DIP32 is the corresponding switch for 32 bits.)

File umf_config.h has more documentation about umfpack compile options,
also no "-DLP64" mentioned there.

Best guess is that SuiteSparse_config.mk should be edited like this:
UMFPACK_CONFIG = -DLP64 -DLONGBLAS=long

I have always installed the pre-built ubuntu package, never tested the above.

PS: For now I am switching to Matlab, where umfpack is built-in.  Thank you so far!!

**Comment by rc** [comment]
Thanks for the information!

**Comment by rc** [comment]
Have a look at #23, please - it seems to work on linux with scipy 0.15.0 + changes from https://github.com/scipy/scipy/pull/6085.

**Comment by RobertKosik** [comment]
Wow, Robert, that is fast.

I will have a closer look in the evening, I am at (other) work just now.

One remark:
Input Matrix to umfpack is quite small (in terms of number of nonzeros in
the matrix).
Only through fill-in it exceeds the 4 GB.

And yes, the sparse matrix object in scipy needs to be fixed (in the long
run), to be able to hold "sparse" matrices with many elements.

In the meanwhile umfpack-wrapper could accept small index type matrix,
but call the dl_versions if asked for by the user. (Did not check, how you
implemented it.)

Thank you - will test and report back in the evening!!

**Comment by rc** [comment]
Note that you need scipy >= 0.14.0 to be able to use int64 as csc/csr matrix indices. And because scipy automatically selects the smallest int to hold the indices (int32 or int64), you need to re-type the ``indptr`` and ``indices`` attributes after the matrix is constructed - see ``_to_int64()`` in ``tests/test_umfpack.py``. In that way, you can force int64 for smaller matrices, so that the factorization could pass. (IMHO - I did not try it with a matrix large enough.)

**Comment by RobertKosik** [comment]
Ah, Robert, thank you for this hint!

So far I thought, this was not supported at all. So the plan was to work with
the low level interface to umfpack and use only the long int arrays (indices, indptr).

Version is 0.15.0.dev. at my private laptop, which I can use for testing.
At work (TCAD applications in academia) it is 0.12 on the server. :-(

I got bitten by this yesterday evening. As you said, the matrix constructor
makes everything int32, even if I pass in all the indices as int64.

I wondered, how you did this. Then I found, it allows me to set the indices and
indptr directly by matrix.indices = matrix.indices.astype(numpy.int64) 

But this is fragile: matrix2 = matrix.copy() is again 32bits. [in 0.15.0.dev]

Will continue on the weekend and see if my large examples work now.

PS: Very proud of myself yesterday, that I could install the new version. :-)
PPS: I think umfpack is fabulous software and has to be available in scipy.

**Comment by rc** [comment]
On 04/22/2016 08:56 AM, RobertKosik wrote:
> Ah, Robert, thank you for this hint!
>
> So far I thought, this was not supported at all. So the plan was to work with
> the low level interface to umfpack and use only the long int arrays (indices, indptr).

Actually the long int support was almost there for a long time. Nevertheless I 
am not sure about the SuiteSparse_long typedef - this could need some care so 
that it is portable.

> Version is 0.15.0.dev. at my private laptop, which I can use for testing.
> At work (TCAD applications in academia) it is 0.12 on the server. :-(
>
> I got bitten by this yesterday evening. As you said, the matrix constructor
> makes everything int32, even if I pass in all the indices as int64.
>
> I wondered, how you did this. Then I found, it allows me to set the indices and
> indptr directly by matrix.indices = matrix.indices.astype(numpy.int64)
>
> But this is fragile: matrix2 = matrix.copy() is again 32bits. [in 0.15.0.dev]

Yes, it is an ad hoc solution - a support in scipy.sparse (preserve_idx_dtype 
flag or something similar) might be needed.

> Will continue on the weekend and see if my larg

e examples work now.
>
> PS: Very proud of myself yesterday, that I could install the new version. :-)

Glad to hear that :)

> PPS: I think umfpack is fabulous software and has to be available in scipy.

Yes, it is very good and robust.

r.

**Comment by rc** [comment]
FYI: https://github.com/scipy/scipy/pull/6085 is merged!

**Comment by rc** [comment]
This should be fixed by #23 now.
