### ISSUE TITLE
Source release of 0.2.2 is missing scikits/__init__.py

### ISSUE THREAD

**Issue by cmutel** [scikit-umfpack/scikit-umfpack#28]
See [conda-forge issue](https://github.com/conda-forge/scikit-umfpack-feedstock/pull/3#issuecomment-229665261). `__init__.py` in the directory `scikits` is missing in `scikit-umfpack-0.2.2.tar.gz`, though it is present is I package a source release myself.
No idea how this is even possible, but should be easy to fix.

**Comment by rc** [comment]
Yes, this is strange - something must have changed in my distutils/setuptools. Anyway, I will do 0.2.3 then.

**Comment by rc** [comment]
Bisecting revealed the culprit: 9d2847130fcf35dd7439bf11d621636c160dc6ae - trying to find the cause.
