### ISSUE TITLE
Documentation on scikit-umfpack.github.io is broken

### ISSUE THREAD

**Issue by pv** [scikit-umfpack/scikit-umfpack#46]
The documentation on https://scikit-umfpack.github.io/scikit-umfpack/ appears broken,
it's missing the actual documentation in the "Contents:" --- "Easy-to-use UMFPACK interface" and
"Low-level interface to UMFPACK".

Apparently, the build somehow failed, eg. without having the correct version of umfpack installed, so .. automodule:: etc directives did not produce any output.

**Comment by rc** [comment]
Thanks for reporting that. I will fix that when making 0.3.1.

**Comment by rc** [comment]
I fixed it for 0.3.0 (0.3.1 is still not ready).

**Comment by rc** [comment]
Fixed now.
