### ISSUE TITLE
update docs/release.rst

### ISSUE THREAD

**Issue by rc** [scikit-umfpack/scikit-umfpack#50]
For 0.3.1 I forgot to set
```
ISRELEASED          = True
```
for the tarball that I uploaded to PyPi ->  improve the instructions in `docs/release.rst`.

**Comment by xoviat** [comment]
You can just update the submodule and push to trigger a build.

**Comment by rc** [comment]
OK, done, thanks!

**Comment by xoviat** [comment]
@rc The wheels are not posted on pypi. Did you have a problem uploading them?

**Comment by rc** [comment]
@xoviat Thanks for reminding me, it should be done now.

**Comment by xoviat** [comment]
Unfortunately, you will need to download the windows wheels directly from appveyor because the key was not added. Questions?

**Comment by xoviat** [comment]
/cc @matthew-brett Please add the API key to appveyor so that we don't have this problem again.

@rc Please add matthew-brett to appveyor.

**Comment by matthew-brett** [comment]
Whose repo is it building on?   I don't think it's mine, or the pythonbloscadmin/python-blosc-wheels repo...

**Comment by xoviat** [comment]
It's `rc/scikit-umfpack` for the appveyor.

**Comment by xoviat** [comment]
You don't have permission currently.

**Comment by rc** [comment]
Isn't it `scikit-umfpack/scikit-umfpack`? I have added @matthew-brett as a collaborator there. Or should I add him to the `scikit-umfpack-wheels` on appveyor? (How?)

As for the windows wheels, I do not see them in the appveyor artifacts tab(?), where IIRC I should be able to find them.

**Comment by xoviat** [comment]
Add to collaborators here: https://ci.appveyor.com/team

**Comment by matthew-brett** [comment]
It's the scikit-umfpack/scikit-umfpack-wheels github repo I think. So, what needs to happen is that someone logged into the  *Appveyor* account that's doing the building - @rc - needs to encrypt the API key.  So @xoviat is right - you need to add me (I have the key) to the `rc` Appveyor account.

**Comment by rc** [comment]
@matthew-brett, thanks - what role should I use - Administrator or User?

**Comment by rc** [comment]
I used User, let me know if I need to add some permissions.

**Comment by xoviat** [comment]
@rc To be clear, you should still be able to upload the wheels by downloading them from the "artifacts" tab. This is to streamline future releases.

**Comment by rc** [comment]
@xoviat I can see the wheels now - I need to click on each job.

**Comment by rc** [comment]
Uploaded!

**Comment by matthew-brett** [comment]
Try:

```
      WHEELHOUSE_UPLOADER_SECRET:
        secure:
            9/K6DI3wjJQrG8sl1m159cdwWpqQZhqPhxIny3V++8UUPVKBU6uKu+D9D47Y1f1+
```

Does that work?

**Comment by rc** [comment]
@matthew-brett thanks for the key, @xoviat thanks for testing that, the windows wheels can be seen on https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com/.
