### ISSUE TITLE
pip install no longer working when Numpy 1.15 is installed

### ISSUE THREAD

**Issue by jgostick** [scikit-umfpack/scikit-umfpack#56]
When I create a fresh conda env with numpy 1.14, I can `pip install scikit-umfpack` not problem at all, but when Numpy 1.15 is installed I get a VERY long error message.  It's too long to post, but the gist of it is:

"No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils"

We use umfpack as a dependency in our package, so our install is now broken! :-(  I guess this is why people specify version numbers in the requirements.txt.  Lesson learned...but hopefully this gets sorted out soon, because we love umfpack!  Thanks.

**Comment by rgommers** [comment]
Let's leave out the pip/conda details here. It seems that your bug report is simply: on Windows, scikit-umfpack cannot be built from source with MSVC. Can you give some more details:
- does this indeed reproduce when you clone this repo and do `python setup.py build`?
- what version of MSVC, SuiteSparse and SWIG are you using, and how did you install those?

**Comment by rgommers** [comment]
>  How do you stay on top of all this!?

I often don't, this week happens to be a good one:)

> When I download the zip file from this repo, unzip, cd to the download dir, and do pip install . it installs just fine, no matter whether I have numpy 1.14 or 1.15.

That helps. This points to a change present in master that's not yet in the last released `scikit-umfpack` version. And that makes sense, the only commit in master that's not in 0.3.1 is https://github.com/scikit-umfpack/scikit-umfpack/commit/a7c5d6d6e7e1e23a4e9862906ce9c3375cc7d96b, which is a Windows build fix. So for now, installing from master you should be fine.

@rc a new release is probably a good idea, if you have some time.

**Comment by rc** [comment]
@rgommers thanks for the fast debugging! I can make a new release, but it might be a good idea to resolve first  #54 and #50 - could somebody review?

**Comment by rgommers** [comment]
done

**Comment by rc** [comment]
Thanks! I have created #57, preparing the release.

**Comment by rc** [comment]
The 0.3.2 release is now on PyPi.

Now https://github.com/scikit-umfpack/scikit-umfpack-wheels needs to be updated, but I managed to forget how :(.

**Comment by jgostick** [comment]
This now works fine for me on my local machine (although it's not working on Travis for some odd reason, but I'm sure that's my fault).
