### ISSUE TITLE
Adding citations to the relevant papers

### ISSUE THREAD

**Issue by DrTimothyAldenDavis** [scikit-umfpack/scikit-umfpack#69]
Can you please add the citations to the relevant papers for UMFPACK, and the ordering methods it relies on (AMD, COLAMD)?  The list of papers is at https://github.com/DrTimothyAldenDavis/SuiteSparse#how-to-cite-the-suitesparse-meta-package-and-its-component-packages .

**Comment by rc** [comment]
Sure, I will prepare a PR. Thanks for making UMFPACK available!

**Comment by rc** [comment]
@DrTimothyAldenDavis I have prepared a PR (#70) - added the latest reference for each of UMFPACK, AMD and COLAMD to the README.rst, sphinx docs and the umfpack.py module docstring. Let me know it that is OK, or you would like more/other papers referenced.
