### ISSUE TITLE
Create new Release (0.3.3)

### ISSUE THREAD

**Issue by michaelweinold** [scikit-umfpack/scikit-umfpack#72]
In order to build an macOS arm64 package of [scikit-umfpack-feedstock](https://github.com/conda-forge/scikit-umfpack-feedstock), it would be great to get a release including the April 2022 commit by @bnavigator ("[use scipy.sparse.linalg function without linsolve namespace](https://github.com/scikit-umfpack/scikit-umfpack/commit/dc890ed824c571c2bac0eec3a420d683e3d6c88b)"), which resolves an issue with the outdated `linsolve` module.

@rc, any chance of a release in the near future?

Compare PR in scikit-umfpack-feedstock: https://github.com/conda-forge/scikit-umfpack-feedstock/pull/30#issuecomment-1203886199

**Comment by michaelweinold** [comment]
Build of [scikit-umfpack-feedstock](https://github.com/conda-forge/scikit-umfpack-feedstock) based on my [own fork of  scikit-umfpack](https://github.com/michaelweinold/scikit-umfpack) successful: https://github.com/conda-forge/scikit-umfpack-feedstock/pull/32

**Comment by rc** [comment]
Hi @michaelweinold, thanks for trying the feedstock. Let us make the release then. I have just created #73.

**Comment by michaelweinold** [comment]
Great, I'll update the source for the feedstock to 

```
{% set version = "0.3.3" %}
git_url: https://github.com/scikit-umfpack/scikit-umfpack
git_tag: {{ version }}
```

as soon as you have the release complete.

**Comment by rc** [comment]
All items from [the release doc](https://scikit-umfpack.github.io/scikit-umfpack/release.html) except 11, 12 (the wheels) are done, so I guess you can proceed.

**Comment by michaelweinold** [comment]
All done, many thanks!
