### ISSUE TITLE
Unable to reuse symbolic factorization for different matrix with same sparsity pattern

### ISSUE THREAD

**Issue by msebregts** [scikit-umfpack/scikit-umfpack#75]
According to the [documentation](https://scikit-umfpack.github.io/scikit-umfpack/umfpack.html), an umfpack context should allow to reuse a symbolic factorization.
However, when doing a new numeric factorization calls `free_numeric`, which then also calls `free_symbolic`. In turn, the symbolic factorization is performed again (unneccesarily).

**Reproduction:**
```Python
import scipy.sparse
import scikits.umfpack as um

mat = scipy.sparse.random(100, 100, 0.1, format="csc")
mat2 = 10*mat  # mat2 has the same sparsity pattern as mat

umfpack = um.UmfpackContext()
# perform symbolic factorization of mat
umfpack.symbolic(mat)
print(umfpack._symbolic)
# perform numeric factorization of mat2, should reuse the symbolic factorization created above
umfpack.numeric(mat2)
print(umfpack._symbolic)  # however, a new symbolic factorization was created!
```

See PR #74 for a suggested fix for this. Let me know if there's any comments or suggestions!

**Comment by rc** [comment]
When I run your test code, I get:
```
<Swig Object of type 'void *' at 0x7fc9482727e0>
<Swig Object of type 'void *' at 0x7fc9482727e0>
```
so it seems the symbolic object is reused. What does it print in your case?

**Comment by rc** [comment]
You are right, the symbolic object is freed when freeing the numeric one - only you need to add one more matrix to your test case.
