### ISSUE TITLE
Use of deprecated `pkg_resources` should be removed

### ISSUE THREAD

**Issue by rgommers** [scikit-umfpack/scikit-umfpack#82]
It's used in an important way, to declare a namespace package, at https://github.com/scikit-umfpack/scikit-umfpack/blob/master/scikits/__init__.py#L1. I stumbled over this in the SciPy CI; pulling in a new `setuptools` version started to emit a ton of deprecation warnings for `pkg_resources`.

I'm not dealing with namespace packages regularly, but I believe that line can simply be deleted; since PEP 420 that should "just work" - see, e.g., https://stackoverflow.com/questions/21819649/namespace-vs-regular-package.

@rc what do you think about making that one-line change and releasing it as either 0.3.4 or 0.4.0?

**Comment by rc** [comment]
Thanks for the verification. So I guess I can also merge #84, right?

**Comment by rgommers** [comment]
Indeed - thanks!

**Comment by rc** [comment]
Hth! This was easy and fast. However there are open issues that I do not have power to resolve. I wonder whether this could be a topic for a GSoC or some other way?

**Comment by rgommers** [comment]
Good question. Besides it being hard to find a student for that, I'm wondering whether that's the best way to go or a bigger overhaul of how sparse solvers are supported makes more sense. UMFPACK is perhaps getting long in the tooth, and it being GPL is quite annoying. I have to admit I don't have a good sense of whether we could replace it with something better (e.g., `petsc4py` is actively maintained but heavy-duty of course, https://github.com/scipy/scipy/issues/14216 discusses PARDISO and whether or not to make other SuiteSparse components available - Cc @mdhaber).

I also don't have a good sense of how much scikit-umfpack still provides when compared to SuperLU and other solvers. I had a quick look, but in SciPy we don't have good benchmarks for a direct comparison. I'd be curious to hear your thoughts on this.

**Comment by rc** [comment]
I have no experience with PARDISO, but FWIW, in sfepy we have a little test/benchmark (Poisson's equation, 9500 unknowns) with the following results:
```
... 0.02 [s] /   57 (2.428e-12) : i13 ls.petsc cg icc
... 0.02 [s] /  157 (2.729e-12) : i12 ls.petsc cg jacobi
... 0.02 [s] /  157 (2.729e-12) : i11 ls.petsc cg python
... 0.02 [s] /  188 (3.289e-12) : i10 ls.petsc cg none
... 0.03 [s] /  188 (3.284e-12) : i20 ls.scipy_iterative cg
... 0.04 [s] /  133 (3.093e-12) : i21 ls.scipy_iterative bicgstab
... 0.04 [s] /  188 (3.478e-12) : i02 ls.pyamg_krylov cg
... 0.07 [s] /  183 (3.580e-12) : i22 ls.scipy_iterative qmr
... 0.09 [s] /   22 (7.553e-13) : i00 ls.pyamg ruge_stuben_solver
... 0.09 [s] /   16 (1.681e-12) : i01 ls.pyamg smoothed_aggregation_solver
... 0.15 [s] /   -1 (6.666e-15) : d10 ls.mumps
... 0.25 [s] /   -1 (4.920e-15) : d01 ls.scipy_direct umfpack
... 0.89 [s] /   -1 (1.489e-14) : d02 ls.scipy_direct superlu
```
Notice the direct solvers - SuperLU, UMFPACK and MUMPS. In my experience, this relative speed holds also for (very) large systems (coming from FEM) - UMFPACK is much faster than SuperLU, and MUMPS is about twice faster than UMFPACK, and also uses less memory. We have custom  ctypes-based MUMPS wrappers in SfePy.

Petsc4py is great, but as you say, it is a large package (including PETSc). On the other hand, all the direct solvers mentioned above can be used via petsc4py. 

I have re-run the test with a once uniformly refined mesh (75000 unknowns):
```
... 0.73 [s] /  118 (3.327e-12) : i13 ls.petsc cg icc
... 0.81 [s] /  340 (4.340e-12) : i12 ls.petsc cg jacobi
... 0.81 [s] /  340 (4.340e-12) : i11 ls.petsc cg python
... 0.94 [s] /   22 (3.877e-12) : i01 ls.pyamg smoothed_aggregation_solver
... 0.97 [s] /  437 (4.005e-12) : i10 ls.petsc cg none
... 1.06 [s] /  440 (4.119e-12) : i02 ls.pyamg_krylov cg
... 1.56 [s] /   49 (2.258e-12) : i00 ls.pyamg ruge_stuben_solver
... 1.80 [s] /  437 (4.023e-12) : i20 ls.scipy_iterative cg
... 2.73 [s] /   -1 (1.103e-14) : d10 ls.mumps
... 3.50 [s] /  312 (4.269e-12) : i21 ls.scipy_iterative bicgstab
... 4.73 [s] /  429 (4.173e-12) : i22 ls.scipy_iterative qmr
... 9.29 [s] /   -1 (7.913e-15) : d01 ls.scipy_direct umfpack
... 152.30 [s] /   -1 (4.859e-14) : d02 ls.scipy_direct superlu
```
So this is my experience.

**Comment by mdhaber** [comment]
This is typical with what I've seen of umfpack and superlu, so I don't think we'd want to get rid of SuperLU. I've also read that MUMPS is often faster than UMFPACK (["An Experimental Comparison of Some Direct Sparse Solver Packages"](https://d1wqtxts1xzle7.cloudfront.net/66495006/ipdps.2001.92518220210421-4322-1rb47ud-libre.pdf?1619063451=&response-content-disposition=inline%3B+filename%3DAn_experimental_comparison_of_some_direc.pdf&Expires=1686953462&Signature=YkBSWwSlMGbYRgG9FfP3z5JBpVci7Dkkfi66BQQGMmhkVav1AeIJe0ItamLMpTSTrn8FkUODyB6KVveMKhpazedbMzkS0Jhh~MG-5HidPv7impJlXFeqZA2970sow93JXIFOL6fFxqgrrVLNnluPzTQi270eyOLEPG0i3Bw5CD0jQusEEY5PzdMP7qO2Y-gEPgNRS51~o6-RBDu2wASR8M82zE4IMEKlZh3wOciGAg6BWqMviNYj0JAkNDKYQ~4J74XXCICFFNxG1yilZ1SKnmZdtji~zJXcpXfnN1cQcuL8wbodJwYmUq30BW8nei2z4tSrHn1wf9hqP9DF8AQbHA__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA)).
