### ISSUE TITLE
Add support for `scipy.sparse.csc_array` and `csr_array`

### ISSUE THREAD

**Issue by rishi-kulkarni** [scikit-umfpack/scikit-umfpack#99]
Currently, these emit warnings and are converted with very low overhead to their matrix counterparts. The array types work fine with the underlying umfpack code, so it seems like this change would just involve expanding some of these type checks:

```
if not (isspmatrix_csc(A) or isspmatrix_csr(A)): ...
```

I'm happy to make a PR for this.

**Comment by rc** [comment]
Thanks for the heads up, a PR would be welcome!

**Comment by rishi-kulkarni** [comment]
Great, I opened #100
